/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    categories: Category;
    articles: Article;
    'pinned-sections': PinnedSection;
    'news-views': NewsView;
    'news-analytics': NewsAnalytic;
    ads: Ad;
    'ad-analytics-daily': AdAnalyticsDaily;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    articles: ArticlesSelect<false> | ArticlesSelect<true>;
    'pinned-sections': PinnedSectionsSelect<false> | PinnedSectionsSelect<true>;
    'news-views': NewsViewsSelect<false> | NewsViewsSelect<true>;
    'news-analytics': NewsAnalyticsSelect<false> | NewsAnalyticsSelect<true>;
    ads: AdsSelect<false> | AdsSelect<true>;
    'ad-analytics-daily': AdAnalyticsDailySelect<false> | AdAnalyticsDailySelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {
    'home-page': HomePage;
    'article-page-layout': ArticlePageLayout;
    'site-sidebar': SiteSidebar;
    'photo-carousel': PhotoCarousel;
    'about-us': AboutUs;
    'terms-of-use': TermsOfUse;
    disclaimer: Disclaimer;
    'privacy-policy': PrivacyPolicy;
    'contact-us': ContactUs;
    'site-ads': SiteAd;
  };
  globalsSelect: {
    'home-page': HomePageSelect<false> | HomePageSelect<true>;
    'article-page-layout': ArticlePageLayoutSelect<false> | ArticlePageLayoutSelect<true>;
    'site-sidebar': SiteSidebarSelect<false> | SiteSidebarSelect<true>;
    'photo-carousel': PhotoCarouselSelect<false> | PhotoCarouselSelect<true>;
    'about-us': AboutUsSelect<false> | AboutUsSelect<true>;
    'terms-of-use': TermsOfUseSelect<false> | TermsOfUseSelect<true>;
    disclaimer: DisclaimerSelect<false> | DisclaimerSelect<true>;
    'privacy-policy': PrivacyPolicySelect<false> | PrivacyPolicySelect<true>;
    'contact-us': ContactUsSelect<false> | ContactUsSelect<true>;
    'site-ads': SiteAdsSelect<false> | SiteAdsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Manage editorial staff and registered readers.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  /**
   * Display name for article bylines and reader profiles.
   */
  name?: string | null;
  role?: ('admin' | 'editor' | 'author' | 'reader') | null;
  /**
   * Short author biography.
   */
  bio?: string | null;
  /**
   * Profile photo.
   */
  avatar?: (string | null) | Media;
  /**
   * Articles saved by this user from the frontend.
   */
  savedArticles?: (string | Article)[] | null;
  preferences?: {
    morningBrief?: boolean | null;
    articleAlerts?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  imageData?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Create and manage news articles. Use Draft/Published status to control live visibility.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles".
 */
export interface Article {
  id: string;
  /**
   * The main headline of the article.
   */
  title: string;
  /**
   * Secondary headline displayed below the title.
   */
  subtitle: string;
  /**
   * Optional summary shown in article cards and previews.
   */
  summary?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Article body. Use the toolbar to insert images, uploaded videos, or YouTube blocks. You can also paste a YouTube URL on its own line.
   */
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Add a quote (optional).
   */
  quotes?: string | null;
  /**
   * Add quotes credits (optional).
   */
  quotesCredits?: string | null;
  hasArticleAudio?: boolean | null;
  /**
   * Add a hero image, an uploaded video, or both. You can also add a YouTube link separately below.
   */
  image?: {
    /**
     * Main photo shown at the top of the article.
     */
    imageAsset?: (string | null) | Media;
    /**
     * MP4/WebM video file for this article (can be used alongside the hero image).
     */
    videoFile?: (string | null) | Media;
    /**
     * Optional thumbnail shown before the uploaded video plays.
     */
    videoPoster?: (string | null) | Media;
  };
  /**
   * Add image credits (optional).
   */
  imageCredits?: string | null;
  /**
   * Toggle to show or hide the photo gallery/carousel on the article page.
   */
  showCarousel?: boolean | null;
  /**
   * Add multiple images to display as a slider/carousel inside this specific article.
   */
  carouselImages?:
    | {
        image: string | Media;
        /**
         * Caption or description for this specific carousel slide.
         */
        caption?: string | null;
        /**
         * Important for accessibility and SEO describing the image.
         */
        altText?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Paste a YouTube URL. Thumbnail preview displays at 9:16 ratio (1080×1920).
   */
  youtubeLink?: string | null;
  youtubeThumbnailUrl?: string | null;
  /**
   * Select one or more articles to display in the "Also Read" section.
   */
  articleHyperlink?: (string | Article)[] | null;
  /**
   * Select one or more categories for this article.
   */
  categories: (string | Category)[];
  /**
   * Add tags in a news article (optional).
   */
  tags?: string[] | null;
  /**
   * Enable to mark this article as eligible for pinning.
   */
  isPinned?: boolean | null;
  /**
   * Select which page view this article should stick to.
   */
  pinnedPage?: ('home' | 'trending' | 'category_top') | null;
  /**
   * URL-friendly identifier. Auto-generated from title. Saved as lowercase with hyphens.
   */
  slug: string;
  approvalStatus?: ('pending' | 'approved' | 'disapproved') | null;
  /**
   * Automatically set to the user who created the article.
   */
  publisher?: string | null;
  /**
   * The author of this article.
   */
  author?: (string | null) | User;
  /**
   * Pick a date/time to schedule, or leave it for instant action. Auto-set when first published.
   */
  publishedAt?: string | null;
  /**
   * Automatically tracked view count.
   */
  viewCount?: number | null;
  /**
   * Auto-calculated from content length.
   */
  estimatedReadingTimeMinutes?: number | null;
  /**
   * Reader reaction counts.
   */
  reactions?: {
    like?: number | null;
    insightful?: number | null;
    sad?: number | null;
    happy?: number | null;
    angry?: number | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: string;
  title: string;
  /**
   * Auto-generated from the title. Used in category URLs.
   */
  slug: string;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Legacy pinned section assignments. Prefer editing pinned articles under Globals → Home Page → Pinned News.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pinned-sections".
 */
export interface PinnedSection {
  id: string;
  section?: ('home' | 'trending' | 'category_top') | null;
  /**
   * Required when the section is "Category Top".
   */
  category?: (string | null) | Category;
  /**
   * Drag items up or down to re-order. Maximum 4 pinned articles allowed here.
   */
  articles?: (string | Article)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Individual article view events used for trending score calculation.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news-views".
 */
export interface NewsView {
  id: string;
  newsId: string | Article;
  updatedAt: string;
  createdAt: string;
}
/**
 * Precomputed trending analytics per article.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news-analytics".
 */
export interface NewsAnalytic {
  id: string;
  newsId: string | Article;
  /**
   * Total share count for this article.
   */
  shares?: number | null;
  /**
   * Total comment count for this article.
   */
  comments?: number | null;
  /**
   * Precomputed trending score. Updated by the background job.
   */
  trendingScore?: number | null;
  lastCalculatedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Trackable ad units linked to Site Ads slots. Creative content is managed in the Site Ads global.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ads".
 */
export interface Ad {
  id: string;
  name: string;
  /**
   * Links this ad unit to a Site Ads slot for tracking.
   */
  slotKey:
    | 'homeLeaderboard'
    | 'homeSidebarTop'
    | 'homeSidebarBottom'
    | 'categoryLeaderboard'
    | 'categoryMidContent'
    | 'categorySidebarTop'
    | 'categorySidebarBottom'
    | 'articleSidebarTop'
    | 'articleSidebarBottom';
  /**
   * Primary placement zone used when this slot is rendered.
   */
  defaultPlacement:
    | 'homepage_top'
    | 'homepage_sidebar'
    | 'homepage_inline'
    | 'article_top'
    | 'article_inline'
    | 'article_footer';
  /**
   * Inactive ads are not tracked on the frontend.
   */
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Aggregated daily ad performance per placement. Updated automatically by tracking endpoints.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ad-analytics-daily".
 */
export interface AdAnalyticsDaily {
  id: string;
  ad: string | Ad;
  /**
   * UTC calendar date in YYYY-MM-DD format.
   */
  date: string;
  placement:
    | 'homepage_top'
    | 'homepage_sidebar'
    | 'homepage_inline'
    | 'article_top'
    | 'article_inline'
    | 'article_footer';
  impressions?: number | null;
  clicks?: number | null;
  /**
   * Click-through rate (%) = (clicks / impressions) × 100
   */
  ctr?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'categories';
        value: string | Category;
      } | null)
    | ({
        relationTo: 'articles';
        value: string | Article;
      } | null)
    | ({
        relationTo: 'pinned-sections';
        value: string | PinnedSection;
      } | null)
    | ({
        relationTo: 'news-views';
        value: string | NewsView;
      } | null)
    | ({
        relationTo: 'news-analytics';
        value: string | NewsAnalytic;
      } | null)
    | ({
        relationTo: 'ads';
        value: string | Ad;
      } | null)
    | ({
        relationTo: 'ad-analytics-daily';
        value: string | AdAnalyticsDaily;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  bio?: T;
  avatar?: T;
  savedArticles?: T;
  preferences?:
    | T
    | {
        morningBrief?: T;
        articleAlerts?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  imageData?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles_select".
 */
export interface ArticlesSelect<T extends boolean = true> {
  title?: T;
  subtitle?: T;
  summary?: T;
  content?: T;
  quotes?: T;
  quotesCredits?: T;
  hasArticleAudio?: T;
  image?:
    | T
    | {
        imageAsset?: T;
        videoFile?: T;
        videoPoster?: T;
      };
  imageCredits?: T;
  showCarousel?: T;
  carouselImages?:
    | T
    | {
        image?: T;
        caption?: T;
        altText?: T;
        id?: T;
      };
  youtubeLink?: T;
  youtubeThumbnailUrl?: T;
  articleHyperlink?: T;
  categories?: T;
  tags?: T;
  isPinned?: T;
  pinnedPage?: T;
  slug?: T;
  approvalStatus?: T;
  publisher?: T;
  author?: T;
  publishedAt?: T;
  viewCount?: T;
  estimatedReadingTimeMinutes?: T;
  reactions?:
    | T
    | {
        like?: T;
        insightful?: T;
        sad?: T;
        happy?: T;
        angry?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pinned-sections_select".
 */
export interface PinnedSectionsSelect<T extends boolean = true> {
  section?: T;
  category?: T;
  articles?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news-views_select".
 */
export interface NewsViewsSelect<T extends boolean = true> {
  newsId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news-analytics_select".
 */
export interface NewsAnalyticsSelect<T extends boolean = true> {
  newsId?: T;
  shares?: T;
  comments?: T;
  trendingScore?: T;
  lastCalculatedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ads_select".
 */
export interface AdsSelect<T extends boolean = true> {
  name?: T;
  slotKey?: T;
  defaultPlacement?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ad-analytics-daily_select".
 */
export interface AdAnalyticsDailySelect<T extends boolean = true> {
  ad?: T;
  date?: T;
  placement?: T;
  impressions?: T;
  clicks?: T;
  ctr?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Control which sections appear on the home page, their order, titles, and content. Drag sections to reorder.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page".
 */
export interface HomePage {
  id: string;
  /**
   * Each block is a section on the home page. Toggle "Show Section" off to hide without deleting content.
   */
  mainSections?:
    | (
        | {
            enabled?: boolean | null;
            ad?: {
              isEnabled?: boolean | null;
              showLabel?: boolean | null;
              labelText?: string | null;
              adType?: ('image' | 'custom') | null;
              sourceType?: ('upload' | 'url') | null;
              imageUpload?: (string | null) | Media;
              /**
               * Paste a direct image URL (used when Image Source is External).
               */
              imageUrl?: string | null;
              /**
               * Where users go when they click the ad image.
               */
              linkUrl?: string | null;
              openInNewTab?: boolean | null;
              altText?: string | null;
              /**
               * Paste ad network code (e.g. Google AdSense) or custom HTML.
               */
              customHtml?: string | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'leaderboardAd';
          }
        | {
            enabled?: boolean | null;
            /**
             * Add, edit, reorder, or remove slides. If empty, the site falls back to the latest published articles.
             */
            photos?:
              | {
                  /**
                   * Optional label shown in admin only (e.g. "Budget 2026").
                   */
                  caption?: string | null;
                  sourceType?: ('upload' | 'url') | null;
                  imageUpload?: (string | null) | Media;
                  /**
                   * Paste a direct image URL.
                   */
                  imageUrl?: string | null;
                  altText?: string | null;
                  /**
                   * When users click this slide they go to this article.
                   */
                  article?: (string | null) | Article;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'photoCarousel';
          }
        | {
            enabled?: boolean | null;
            sectionTitle: string;
            showCount?: boolean | null;
            /**
             * Add, edit, reorder, or remove pinned articles. Maximum 4.
             */
            pinnedItems?:
              | {
                  article: string | Article;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'pinnedNews';
          }
        | {
            enabled?: boolean | null;
            sectionTitle: string;
            limit: number;
            id?: string | null;
            blockName?: string | null;
            blockType: 'trendingNews';
          }
        | {
            enabled?: boolean | null;
            sectionTitle: string;
            perPage: number;
            id?: string | null;
            blockName?: string | null;
            blockType: 'latestNews';
          }
      )[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Manage article detail page layout: page sections and the shared content display order for all articles.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "article-page-layout".
 */
export interface ArticlePageLayout {
  id: string;
  /**
   * Drag to reorder page-level sections. Toggle "Show Section" to hide without removing.
   */
  sections?:
    | (
        | {
            enabled?: boolean | null;
            info?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'breadcrumbs';
          }
        | {
            enabled?: boolean | null;
            info?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'metaHeader';
          }
        | {
            enabled?: boolean | null;
            info?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'articleContent';
          }
        | {
            enabled?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'tags';
          }
        | {
            enabled?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'reactions';
          }
        | {
            enabled?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'shareBar';
          }
        | {
            enabled?: boolean | null;
            sectionTitle: string;
            /**
             * Articles come from each article's "Also Read" / hyperlink fields in the Articles collection.
             */
            contentInfo?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'alsoRead';
          }
      )[]
    | null;
  /**
   * All content blocks are listed below. Drag to reorder, or toggle "Show Section" to hide a block.
   */
  displayOrder?:
    | (
        | {
            enabled?: boolean | null;
            info?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'title';
          }
        | {
            enabled?: boolean | null;
            info?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'subtitle';
          }
        | {
            enabled?: boolean | null;
            info?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'summary';
          }
        | {
            enabled?: boolean | null;
            info?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'byline';
          }
        | {
            enabled?: boolean | null;
            info?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'shareActions';
          }
        | {
            enabled?: boolean | null;
            info?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'articleAudio';
          }
        | {
            enabled?: boolean | null;
            info?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'heroImage';
          }
        | {
            enabled?: boolean | null;
            info?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'heroVideo';
          }
        | {
            enabled?: boolean | null;
            info?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'youtubeVideo';
          }
        | {
            enabled?: boolean | null;
            info?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'photoCarousel';
          }
        | {
            enabled?: boolean | null;
            info?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'quotes';
          }
        | {
            enabled?: boolean | null;
            info?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'body';
          }
      )[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Shared sidebar shown on home, article, and category pages. Configure ads, Morning Brief, and category news blocks once.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-sidebar".
 */
export interface SiteSidebar {
  id: string;
  showTopAd?: boolean | null;
  topAd?: {
    isEnabled?: boolean | null;
    showLabel?: boolean | null;
    labelText?: string | null;
    adType?: ('image' | 'custom') | null;
    sourceType?: ('upload' | 'url') | null;
    imageUpload?: (string | null) | Media;
    /**
     * Paste a direct image URL (used when Image Source is External).
     */
    imageUrl?: string | null;
    /**
     * Where users go when they click the ad image.
     */
    linkUrl?: string | null;
    openInNewTab?: boolean | null;
    altText?: string | null;
    /**
     * Paste ad network code (e.g. Google AdSense) or custom HTML.
     */
    customHtml?: string | null;
  };
  showMorningBrief?: boolean | null;
  showCategoryNews?: boolean | null;
  /**
   * Add up to 3 category blocks. Pick a category, then choose up to 3 articles from that category.
   */
  categorySections?:
    | {
        enabled?: boolean | null;
        category: string | Category;
        /**
         * Pick up to 3 published articles from the selected category.
         */
        articles?: (string | Article)[] | null;
        id?: string | null;
      }[]
    | null;
  showBottomAd?: boolean | null;
  bottomAd?: {
    isEnabled?: boolean | null;
    showLabel?: boolean | null;
    labelText?: string | null;
    adType?: ('image' | 'custom') | null;
    sourceType?: ('upload' | 'url') | null;
    imageUpload?: (string | null) | Media;
    /**
     * Paste a direct image URL (used when Image Source is External).
     */
    imageUrl?: string | null;
    /**
     * Where users go when they click the ad image.
     */
    linkUrl?: string | null;
    openInNewTab?: boolean | null;
    altText?: string | null;
    /**
     * Paste ad network code (e.g. Google AdSense) or custom HTML.
     */
    customHtml?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Legacy carousel settings. Prefer editing slides under Globals → Home Page → Photo Carousel.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "photo-carousel".
 */
export interface PhotoCarousel {
  id: string;
  /**
   * Toggle ON to display the carousel. Toggle OFF to hide it without deleting your photos.
   */
  isEnabled?: boolean | null;
  /**
   * Add, remove, or reorder photos in the carousel. Maximum 4 photos allowed.
   */
  photos?:
    | {
        sourceType?: ('upload' | 'url') | null;
        imageUpload?: (string | null) | Media;
        /**
         * Paste a direct image URL.
         */
        imageUrl?: string | null;
        altText?: string | null;
        /**
         * When users click this slide they will be redirected to this article.
         */
        article?: (string | null) | Article;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Manage the content of the About Us page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-us".
 */
export interface AboutUs {
  id: string;
  whereBusinessSpeaksGujarati: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  ourStory: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  whatWeCover?:
    | {
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  ourValues?:
    | {
        value: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  ourVision?: {
    descriptions?:
      | {
          description: string;
          id?: string | null;
        }[]
      | null;
    tagline?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Manage the content of the Terms of Use page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "terms-of-use".
 */
export interface TermsOfUse {
  id: string;
  pageTitle: string;
  /**
   * Displayed below the page title when enabled on the frontend.
   */
  lastUpdated?: string | null;
  /**
   * Opening paragraph shown at the top of the page.
   */
  intro?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Optional highlighted callout box.
   */
  importantNotice?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Add, remove, or reorder terms of use sections.
   */
  sections?:
    | {
        /**
         * Optional. e.g. "2.1", "2.2". Shown before the title.
         */
        sectionNumber?: string | null;
        title: string;
        content: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Manage the content of the Disclaimer page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "disclaimer".
 */
export interface Disclaimer {
  id: string;
  pageTitle: string;
  /**
   * Displayed below the page title when enabled on the frontend.
   */
  lastUpdated?: string | null;
  /**
   * Opening paragraph shown at the top of the page.
   */
  intro?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Optional highlighted callout box.
   */
  importantNotice?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Add, remove, or reorder disclaimer sections.
   */
  sections?:
    | {
        /**
         * Optional. e.g. "2.1", "2.2". Shown before the title.
         */
        sectionNumber?: string | null;
        title: string;
        content: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Manage the content of the Privacy Policy page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "privacy-policy".
 */
export interface PrivacyPolicy {
  id: string;
  pageTitle: string;
  lastUpdated?: string | null;
  /**
   * Add privacy policy sections. Use Content Section for text/lists, Cookies Policy for the cookie grid, and Grievance Officer for contact details.
   */
  sections?:
    | (
        | {
            /**
             * e.g. "1.1", "1.2", or "1.2.1"
             */
            sectionNumber?: string | null;
            title: string;
            content: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'contentSection';
          }
        | {
            sectionNumber?: string | null;
            title: string;
            intro?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            /**
             * Displayed in a 2-column grid (e.g. Essential, Analytics, Preference, Marketing).
             */
            cookieTypes?:
              | {
                  title: string;
                  description: string;
                  /**
                   * Small tag shown below the description, e.g. "KuberaNow" or "Google Analytics / third-party".
                   */
                  managedBy?: string | null;
                  id?: string | null;
                }[]
              | null;
            /**
             * Text shown below the cookie type grid.
             */
            footer?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'cookiesPolicy';
          }
        | {
            sectionNumber?: string | null;
            title: string;
            intro?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            officerName?: string | null;
            designation?: string | null;
            email?: string | null;
            address?: string | null;
            responseTime?: string | null;
            closing?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'grievanceOfficer';
          }
      )[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Manage the Contact Us page content and contact details.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-us".
 */
export interface ContactUs {
  id: string;
  pageTitle: string;
  /**
   * Shown in the banner below the page title. Prefix with "Response Commitment:" if desired.
   */
  responseCommitment?: string | null;
  /**
   * First 3 cards appear in a 3-column row; remaining cards use a 2-column row.
   */
  contactCards?:
    | {
        /**
         * Upload an icon image (SVG or PNG). Displayed in the maroon icon box on the card.
         */
        iconImage?: (string | null) | Media;
        title: string;
        description?: string | null;
        details?:
          | {
              /**
               * e.g. Email, Phone, WhatsApp, Ofc Hours
               */
              label: string;
              value: string;
              /**
               * Show the value in brand red (recommended for email addresses).
               */
              highlightValue?: boolean | null;
              id?: string | null;
            }[]
          | null;
        /**
         * Optional small note shown at the bottom of the card.
         */
        footnote?: string | null;
        id?: string | null;
      }[]
    | null;
  grievanceSection?: {
    title?: string | null;
    description?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    /**
     * Timeline cards in the grievance section. Add as many as needed (e.g. Acknowledgement, Resolution).
     */
    slaBoxes?:
      | {
          label: string;
          /**
           * Large gold value (e.g. "24 Hrs", "15 Days").
           */
          value: string;
          /**
           * Small line below the value (e.g. "from receipt").
           */
          subtitle?: string | null;
          id?: string | null;
        }[]
      | null;
    officerDetails?:
      | {
          label: string;
          value: string;
          id?: string | null;
        }[]
      | null;
    /**
     * Shown in the note box at the bottom right of the grievance section.
     */
    submissionNote?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Manage advertisement slots across home, category, and article pages. Each slot supports image ads or custom HTML/scripts.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-ads".
 */
export interface SiteAd {
  id: string;
  homeLeaderboard?: {
    isEnabled?: boolean | null;
    showLabel?: boolean | null;
    labelText?: string | null;
    adType?: ('image' | 'custom') | null;
    sourceType?: ('upload' | 'url') | null;
    imageUpload?: (string | null) | Media;
    /**
     * Paste a direct image URL (used when Image Source is External).
     */
    imageUrl?: string | null;
    /**
     * Where users go when they click the ad image.
     */
    linkUrl?: string | null;
    openInNewTab?: boolean | null;
    altText?: string | null;
    /**
     * Paste ad network code (e.g. Google AdSense) or custom HTML.
     */
    customHtml?: string | null;
  };
  homeSidebarTop?: {
    isEnabled?: boolean | null;
    showLabel?: boolean | null;
    labelText?: string | null;
    adType?: ('image' | 'custom') | null;
    sourceType?: ('upload' | 'url') | null;
    imageUpload?: (string | null) | Media;
    /**
     * Paste a direct image URL (used when Image Source is External).
     */
    imageUrl?: string | null;
    /**
     * Where users go when they click the ad image.
     */
    linkUrl?: string | null;
    openInNewTab?: boolean | null;
    altText?: string | null;
    /**
     * Paste ad network code (e.g. Google AdSense) or custom HTML.
     */
    customHtml?: string | null;
  };
  homeSidebarBottom?: {
    isEnabled?: boolean | null;
    showLabel?: boolean | null;
    labelText?: string | null;
    adType?: ('image' | 'custom') | null;
    sourceType?: ('upload' | 'url') | null;
    imageUpload?: (string | null) | Media;
    /**
     * Paste a direct image URL (used when Image Source is External).
     */
    imageUrl?: string | null;
    /**
     * Where users go when they click the ad image.
     */
    linkUrl?: string | null;
    openInNewTab?: boolean | null;
    altText?: string | null;
    /**
     * Paste ad network code (e.g. Google AdSense) or custom HTML.
     */
    customHtml?: string | null;
  };
  categoryLeaderboard?: {
    isEnabled?: boolean | null;
    showLabel?: boolean | null;
    labelText?: string | null;
    adType?: ('image' | 'custom') | null;
    sourceType?: ('upload' | 'url') | null;
    imageUpload?: (string | null) | Media;
    /**
     * Paste a direct image URL (used when Image Source is External).
     */
    imageUrl?: string | null;
    /**
     * Where users go when they click the ad image.
     */
    linkUrl?: string | null;
    openInNewTab?: boolean | null;
    altText?: string | null;
    /**
     * Paste ad network code (e.g. Google AdSense) or custom HTML.
     */
    customHtml?: string | null;
  };
  categoryMidContent?: {
    isEnabled?: boolean | null;
    showLabel?: boolean | null;
    labelText?: string | null;
    adType?: ('image' | 'custom') | null;
    sourceType?: ('upload' | 'url') | null;
    imageUpload?: (string | null) | Media;
    /**
     * Paste a direct image URL (used when Image Source is External).
     */
    imageUrl?: string | null;
    /**
     * Where users go when they click the ad image.
     */
    linkUrl?: string | null;
    openInNewTab?: boolean | null;
    altText?: string | null;
    /**
     * Paste ad network code (e.g. Google AdSense) or custom HTML.
     */
    customHtml?: string | null;
  };
  categorySidebarTop?: {
    isEnabled?: boolean | null;
    showLabel?: boolean | null;
    labelText?: string | null;
    adType?: ('image' | 'custom') | null;
    sourceType?: ('upload' | 'url') | null;
    imageUpload?: (string | null) | Media;
    /**
     * Paste a direct image URL (used when Image Source is External).
     */
    imageUrl?: string | null;
    /**
     * Where users go when they click the ad image.
     */
    linkUrl?: string | null;
    openInNewTab?: boolean | null;
    altText?: string | null;
    /**
     * Paste ad network code (e.g. Google AdSense) or custom HTML.
     */
    customHtml?: string | null;
  };
  categorySidebarBottom?: {
    isEnabled?: boolean | null;
    showLabel?: boolean | null;
    labelText?: string | null;
    adType?: ('image' | 'custom') | null;
    sourceType?: ('upload' | 'url') | null;
    imageUpload?: (string | null) | Media;
    /**
     * Paste a direct image URL (used when Image Source is External).
     */
    imageUrl?: string | null;
    /**
     * Where users go when they click the ad image.
     */
    linkUrl?: string | null;
    openInNewTab?: boolean | null;
    altText?: string | null;
    /**
     * Paste ad network code (e.g. Google AdSense) or custom HTML.
     */
    customHtml?: string | null;
  };
  articleSidebarTop?: {
    isEnabled?: boolean | null;
    showLabel?: boolean | null;
    labelText?: string | null;
    adType?: ('image' | 'custom') | null;
    sourceType?: ('upload' | 'url') | null;
    imageUpload?: (string | null) | Media;
    /**
     * Paste a direct image URL (used when Image Source is External).
     */
    imageUrl?: string | null;
    /**
     * Where users go when they click the ad image.
     */
    linkUrl?: string | null;
    openInNewTab?: boolean | null;
    altText?: string | null;
    /**
     * Paste ad network code (e.g. Google AdSense) or custom HTML.
     */
    customHtml?: string | null;
  };
  articleSidebarBottom?: {
    isEnabled?: boolean | null;
    showLabel?: boolean | null;
    labelText?: string | null;
    adType?: ('image' | 'custom') | null;
    sourceType?: ('upload' | 'url') | null;
    imageUpload?: (string | null) | Media;
    /**
     * Paste a direct image URL (used when Image Source is External).
     */
    imageUrl?: string | null;
    /**
     * Where users go when they click the ad image.
     */
    linkUrl?: string | null;
    openInNewTab?: boolean | null;
    altText?: string | null;
    /**
     * Paste ad network code (e.g. Google AdSense) or custom HTML.
     */
    customHtml?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page_select".
 */
export interface HomePageSelect<T extends boolean = true> {
  mainSections?:
    | T
    | {
        leaderboardAd?:
          | T
          | {
              enabled?: T;
              ad?:
                | T
                | {
                    isEnabled?: T;
                    showLabel?: T;
                    labelText?: T;
                    adType?: T;
                    sourceType?: T;
                    imageUpload?: T;
                    imageUrl?: T;
                    linkUrl?: T;
                    openInNewTab?: T;
                    altText?: T;
                    customHtml?: T;
                  };
              id?: T;
              blockName?: T;
            };
        photoCarousel?:
          | T
          | {
              enabled?: T;
              photos?:
                | T
                | {
                    caption?: T;
                    sourceType?: T;
                    imageUpload?: T;
                    imageUrl?: T;
                    altText?: T;
                    article?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        pinnedNews?:
          | T
          | {
              enabled?: T;
              sectionTitle?: T;
              showCount?: T;
              pinnedItems?:
                | T
                | {
                    article?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        trendingNews?:
          | T
          | {
              enabled?: T;
              sectionTitle?: T;
              limit?: T;
              id?: T;
              blockName?: T;
            };
        latestNews?:
          | T
          | {
              enabled?: T;
              sectionTitle?: T;
              perPage?: T;
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "article-page-layout_select".
 */
export interface ArticlePageLayoutSelect<T extends boolean = true> {
  sections?:
    | T
    | {
        breadcrumbs?:
          | T
          | {
              enabled?: T;
              info?: T;
              id?: T;
              blockName?: T;
            };
        metaHeader?:
          | T
          | {
              enabled?: T;
              info?: T;
              id?: T;
              blockName?: T;
            };
        articleContent?:
          | T
          | {
              enabled?: T;
              info?: T;
              id?: T;
              blockName?: T;
            };
        tags?:
          | T
          | {
              enabled?: T;
              id?: T;
              blockName?: T;
            };
        reactions?:
          | T
          | {
              enabled?: T;
              id?: T;
              blockName?: T;
            };
        shareBar?:
          | T
          | {
              enabled?: T;
              id?: T;
              blockName?: T;
            };
        alsoRead?:
          | T
          | {
              enabled?: T;
              sectionTitle?: T;
              contentInfo?: T;
              id?: T;
              blockName?: T;
            };
      };
  displayOrder?:
    | T
    | {
        title?:
          | T
          | {
              enabled?: T;
              info?: T;
              id?: T;
              blockName?: T;
            };
        subtitle?:
          | T
          | {
              enabled?: T;
              info?: T;
              id?: T;
              blockName?: T;
            };
        summary?:
          | T
          | {
              enabled?: T;
              info?: T;
              id?: T;
              blockName?: T;
            };
        byline?:
          | T
          | {
              enabled?: T;
              info?: T;
              id?: T;
              blockName?: T;
            };
        shareActions?:
          | T
          | {
              enabled?: T;
              info?: T;
              id?: T;
              blockName?: T;
            };
        articleAudio?:
          | T
          | {
              enabled?: T;
              info?: T;
              id?: T;
              blockName?: T;
            };
        heroImage?:
          | T
          | {
              enabled?: T;
              info?: T;
              id?: T;
              blockName?: T;
            };
        heroVideo?:
          | T
          | {
              enabled?: T;
              info?: T;
              id?: T;
              blockName?: T;
            };
        youtubeVideo?:
          | T
          | {
              enabled?: T;
              info?: T;
              id?: T;
              blockName?: T;
            };
        photoCarousel?:
          | T
          | {
              enabled?: T;
              info?: T;
              id?: T;
              blockName?: T;
            };
        quotes?:
          | T
          | {
              enabled?: T;
              info?: T;
              id?: T;
              blockName?: T;
            };
        body?:
          | T
          | {
              enabled?: T;
              info?: T;
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-sidebar_select".
 */
export interface SiteSidebarSelect<T extends boolean = true> {
  showTopAd?: T;
  topAd?:
    | T
    | {
        isEnabled?: T;
        showLabel?: T;
        labelText?: T;
        adType?: T;
        sourceType?: T;
        imageUpload?: T;
        imageUrl?: T;
        linkUrl?: T;
        openInNewTab?: T;
        altText?: T;
        customHtml?: T;
      };
  showMorningBrief?: T;
  showCategoryNews?: T;
  categorySections?:
    | T
    | {
        enabled?: T;
        category?: T;
        articles?: T;
        id?: T;
      };
  showBottomAd?: T;
  bottomAd?:
    | T
    | {
        isEnabled?: T;
        showLabel?: T;
        labelText?: T;
        adType?: T;
        sourceType?: T;
        imageUpload?: T;
        imageUrl?: T;
        linkUrl?: T;
        openInNewTab?: T;
        altText?: T;
        customHtml?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "photo-carousel_select".
 */
export interface PhotoCarouselSelect<T extends boolean = true> {
  isEnabled?: T;
  photos?:
    | T
    | {
        sourceType?: T;
        imageUpload?: T;
        imageUrl?: T;
        altText?: T;
        article?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-us_select".
 */
export interface AboutUsSelect<T extends boolean = true> {
  whereBusinessSpeaksGujarati?: T;
  ourStory?: T;
  whatWeCover?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  ourValues?:
    | T
    | {
        value?: T;
        description?: T;
        id?: T;
      };
  ourVision?:
    | T
    | {
        descriptions?:
          | T
          | {
              description?: T;
              id?: T;
            };
        tagline?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "terms-of-use_select".
 */
export interface TermsOfUseSelect<T extends boolean = true> {
  pageTitle?: T;
  lastUpdated?: T;
  intro?: T;
  importantNotice?: T;
  sections?:
    | T
    | {
        sectionNumber?: T;
        title?: T;
        content?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "disclaimer_select".
 */
export interface DisclaimerSelect<T extends boolean = true> {
  pageTitle?: T;
  lastUpdated?: T;
  intro?: T;
  importantNotice?: T;
  sections?:
    | T
    | {
        sectionNumber?: T;
        title?: T;
        content?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "privacy-policy_select".
 */
export interface PrivacyPolicySelect<T extends boolean = true> {
  pageTitle?: T;
  lastUpdated?: T;
  sections?:
    | T
    | {
        contentSection?:
          | T
          | {
              sectionNumber?: T;
              title?: T;
              content?: T;
              id?: T;
              blockName?: T;
            };
        cookiesPolicy?:
          | T
          | {
              sectionNumber?: T;
              title?: T;
              intro?: T;
              cookieTypes?:
                | T
                | {
                    title?: T;
                    description?: T;
                    managedBy?: T;
                    id?: T;
                  };
              footer?: T;
              id?: T;
              blockName?: T;
            };
        grievanceOfficer?:
          | T
          | {
              sectionNumber?: T;
              title?: T;
              intro?: T;
              officerName?: T;
              designation?: T;
              email?: T;
              address?: T;
              responseTime?: T;
              closing?: T;
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-us_select".
 */
export interface ContactUsSelect<T extends boolean = true> {
  pageTitle?: T;
  responseCommitment?: T;
  contactCards?:
    | T
    | {
        iconImage?: T;
        title?: T;
        description?: T;
        details?:
          | T
          | {
              label?: T;
              value?: T;
              highlightValue?: T;
              id?: T;
            };
        footnote?: T;
        id?: T;
      };
  grievanceSection?:
    | T
    | {
        title?: T;
        description?: T;
        slaBoxes?:
          | T
          | {
              label?: T;
              value?: T;
              subtitle?: T;
              id?: T;
            };
        officerDetails?:
          | T
          | {
              label?: T;
              value?: T;
              id?: T;
            };
        submissionNote?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-ads_select".
 */
export interface SiteAdsSelect<T extends boolean = true> {
  homeLeaderboard?:
    | T
    | {
        isEnabled?: T;
        showLabel?: T;
        labelText?: T;
        adType?: T;
        sourceType?: T;
        imageUpload?: T;
        imageUrl?: T;
        linkUrl?: T;
        openInNewTab?: T;
        altText?: T;
        customHtml?: T;
      };
  homeSidebarTop?:
    | T
    | {
        isEnabled?: T;
        showLabel?: T;
        labelText?: T;
        adType?: T;
        sourceType?: T;
        imageUpload?: T;
        imageUrl?: T;
        linkUrl?: T;
        openInNewTab?: T;
        altText?: T;
        customHtml?: T;
      };
  homeSidebarBottom?:
    | T
    | {
        isEnabled?: T;
        showLabel?: T;
        labelText?: T;
        adType?: T;
        sourceType?: T;
        imageUpload?: T;
        imageUrl?: T;
        linkUrl?: T;
        openInNewTab?: T;
        altText?: T;
        customHtml?: T;
      };
  categoryLeaderboard?:
    | T
    | {
        isEnabled?: T;
        showLabel?: T;
        labelText?: T;
        adType?: T;
        sourceType?: T;
        imageUpload?: T;
        imageUrl?: T;
        linkUrl?: T;
        openInNewTab?: T;
        altText?: T;
        customHtml?: T;
      };
  categoryMidContent?:
    | T
    | {
        isEnabled?: T;
        showLabel?: T;
        labelText?: T;
        adType?: T;
        sourceType?: T;
        imageUpload?: T;
        imageUrl?: T;
        linkUrl?: T;
        openInNewTab?: T;
        altText?: T;
        customHtml?: T;
      };
  categorySidebarTop?:
    | T
    | {
        isEnabled?: T;
        showLabel?: T;
        labelText?: T;
        adType?: T;
        sourceType?: T;
        imageUpload?: T;
        imageUrl?: T;
        linkUrl?: T;
        openInNewTab?: T;
        altText?: T;
        customHtml?: T;
      };
  categorySidebarBottom?:
    | T
    | {
        isEnabled?: T;
        showLabel?: T;
        labelText?: T;
        adType?: T;
        sourceType?: T;
        imageUpload?: T;
        imageUrl?: T;
        linkUrl?: T;
        openInNewTab?: T;
        altText?: T;
        customHtml?: T;
      };
  articleSidebarTop?:
    | T
    | {
        isEnabled?: T;
        showLabel?: T;
        labelText?: T;
        adType?: T;
        sourceType?: T;
        imageUpload?: T;
        imageUrl?: T;
        linkUrl?: T;
        openInNewTab?: T;
        altText?: T;
        customHtml?: T;
      };
  articleSidebarBottom?:
    | T
    | {
        isEnabled?: T;
        showLabel?: T;
        labelText?: T;
        adType?: T;
        sourceType?: T;
        imageUpload?: T;
        imageUrl?: T;
        linkUrl?: T;
        openInNewTab?: T;
        altText?: T;
        customHtml?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}